version: '2'
services:
  task_manager_db:
    image: postgres
  task_manager_web:
    build: .
    command: foreman start -p 3000
    volumes:
      - .:/task_manager
    ports:
      - "3000:3000"
      - "4000:4000"
    depends_on:
      - task_manager_db
